defaults:
  - trainable: mnist
  - dataset: mnist
  - _self_

data_loader:
  per_device_batch_size: 32
  worker_count: 8
  worker_buffer_size: 8
  num_epochs: null

trainer:
  num_steps: 100_000
  log_every: 100
  on_existing_workspace: restore
  checkpointing:
    save_interval_steps: 1000
    max_to_keep: 3

seed: 0
