defaults:
  - trainable: mnist
  - dataset: mnist
  - _self_

data_loader:
  per_device_batch_size: 32
  worker_count: 0
  worker_buffer_size: 0
  num_epochs: null

trainer:
  num_steps: 100_000
  checkpointing:
    save_interval_steps: 1000
    max_to_keep: 3

seed: 0
